#!/bin/bash
# ===========================================================================
#    Automated script generated by the CSB server for PRODIGY execution
# ===========================================================================
# August 03, 2023 09:54:38 UTC
# ===========================================================================
outputfile="output.out"

echo "# ===========================================================================" &>> $outputfile
log="receptor.log"


cmd="/usr/local/bin/prodigy receptor.pdb --selection A C --temperature 36.0 --contact_list --pymol_selection"

echo "command: $cmd" &>> $outputfile

$cmd &> $log
status=$?
echo "exit status: $status" &>> $outputfile
echo "log:" &>> $outputfile
cat $log >> $outputfile


exit $status
# ===========================================================================